# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'iOSCare+MVVM+SnapKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSCare+MVVM+SnapKit

  pod 'Alamofire'
  pod 'SnapKit'
  pod 'Kingfisher', '~> 5.0'
  pod 'SwiftLint'

end
